### ISSUE TITLE
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/quantlibnode/quantlibnode/releases /download/v0.1.4/win32-x64.tar.gz

### ISSUE THREAD

**Issue by grandtiger** [quantlibnode/quantlibnode#1]
Thanks for sharing this! I think this would be a great addition to the QuantLib community. However, I got errors when I tried to install it. Could you please look into this when you get the chance? Have a happy new year!

```
D:\temp\quantlib>npm install quantlib

> quantlib@0.1.4 postinstall D:\temp\node_modules\quantlib
> node-pre-gyp install

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/quantlibnode/quantlibnode/releases
/download/v0.1.4/win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (D:\temp\node_modules\node-pre-gyp\lib\install.js:120:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:188:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (D:\temp\node_modules\request\request.js:986:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\temp\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp
" "install"
node-pre-gyp ERR! cwd D:\temp\node_modules\quantlib
node-pre-gyp ERR! node -v v6.9.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
404 status code downloading tarball https://github.com/quantlibnode/quantlibnode/releases/download/v0.1.4/win32-x64.tar.
gz
npm WARN Error: EPERM: operation not permitted, scandir 'D:\temp\node_modules\getpass\node_modules'
npm WARN     at Error (native)
npm WARN  { Error: EPERM: operation not permitted, scandir 'D:\temp\node_modules\getpass\node_modules'
npm WARN     at Error (native)
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'D:\\temp\\node_modules\\getpass\\node_modules' }
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\f401036\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\
npm-cli.js" "install" "quantlib"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! quantlib@0.1.4 postinstall: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quantlib@0.1.4 postinstall script 'node-pre-gyp install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the quantlib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs quantlib
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls quantlib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\temp\quantlib\npm-debug.log
```

**Comment by quantjin** [comment]
Hi George

Thank you for your interest in this project and report this issue!

I've uploaded the README.md with building process, for now only win32
pre-built addon is available, I will try to build and upload win64 when I
got the chance.

For now, please follow instructions here:
https://github.com/quantlibnode/quantlibnode#building-the-native-addon

And let me know if you come across any issue while building the addon

Happy New Year!

Regards
Jerry

**Comment by grandtiger** [comment]
Thanks a lot, Jerry!

I'll give it a try today and see how it goes.

It'll be the first time I build a native module (and a very complicated one) from source. I'll ask you again if I run into any issues.

Take care!

Regards,
George

**Comment by quantjin** [comment]
@grandtiger , v0.2.1 published, with both win32 & win64 prebuilt, please try the latest version
